#include <iostream>
#include "Money.h"
using namespace std;
int main(){
    Money Money1, Money2;
    std::cout << "Money Class Test Program" << std::endl;
    std::cout << std::endl;
    std::cout << "Input/Output" << std::endl;
    std::cout << "Enter Money 1 (Dollars & Cents):" << std::endl;
    std::cin >> Money1;
    std::cout << "Money 1: " << Money1 << std::endl;
    std::cout << "Enter Money 2 (Dollars & Cents):" << std::endl;
    std::cin >> Money2;
    std::cout << "Money 2: " << Money2 << std::endl;
    std::cout << std::endl;
    std::cout << "Basic Operators" << std:: endl;
    std::cout << "Money 1 + Money 2 Result: " << Money1 + Money2 << std::endl;
    std::cout << "Money 1 - Money 2 Result: " << Money1 - Money2 << std::endl;
    std::cout << "Money 1 * Money 2 Result: " << Money1 * Money2 << std::endl;
    std::cout << "Money 1 / Money 2 Result: " << Money1 / Money2 << std::endl;
    std::cout << std::endl;
    std::cout << "Friend Function Increments" << std::endl;
    std::cout << "[Before] Prefix Increment Money 1: " << ++Money1 << std::endl;
    std::cout << "[After] Prefix Increment Money 1: " << Money1 << std::endl;
    std::cout << "[Before] Postfix Increment Money 1: " << Money1++ << std::endl;
    std::cout << "[After] Postfix Increment Money 1: " << Money1 << std::endl;
    std::cout << "[Before] Prefix Increment Money 2: " << ++Money2 << std::endl;
    std::cout << "[After] Prefix Increment Money 2: " << Money2 << std::endl;
    std::cout << "[Before] Postfix Increment Money 2: " << Money2++ << std::endl;
    std::cout << "[After] Postfix Increment Money 2: " << Money2 << std::endl;
    std::cout << std::endl;
    std::cout << "Method Function Decrements" << std::endl;
    std::cout << "[Before] Prefix Decrement Money 1: " << --Money1 << std::endl;
    std::cout << "[After] Prefix Decrement Money 1: " << Money1 << std::endl;
    std::cout << "[Before] Postfix Decrement Money 1: " << Money1-- << std::endl;
    std::cout << "[After] Postfix Decrement Money 1: " << Money1 << std::endl;
    std::cout << "[Before] Prefix Decrement Money 2: " << --Money2 << std::endl;
    std::cout << "[After] Prefix Decrement Money 2: " << Money2 << std::endl;
    std::cout << "[Before] Postfix Decrement Money 2: " << Money2-- << std::endl;
    std::cout << "[After] Postfix Decrement Money 2: " << Money2 << std::endl;
    std::cout << std::endl;
    std::cout << "Equality Operators" << std::endl;
    std::cout << "Money 1 == Money 2: " << Money1 << " == " << Money2 << " : " << (Money1 == Money2 ? "True" : "False") << std::endl;
    std::cout << "Money 1 != Money 2: " << Money1 << " != " << Money2 << " : " << (Money1 != Money2 ? "True" : "False") << std::endl;
    std::cout << "Money 1 > Money 2: " << Money1 << " > " << Money2 << " : " << (Money1 > Money2 ? "True" : "False") << std::endl;
    std::cout << "Money 1 < Money 2: " << Money1 << " < " << Money2 << " : " << (Money1 < Money2 ? "True" : "False") << std::endl;
    std::cout << "Money 1 >= Money 2: " << Money1 << " >= " << Money2 << " : " << (Money1 >= Money2 ? "True" : "False") << std::endl;
    std::cout << "Money 1 <= Money 2: " << Money1 << " <= " << Money2 << " : " << (Money1 <= Money2 ? "True" : "False") << std::endl;
    return 0;
};
