#include <iostream>
#include "Queue.h"
using namespace std;
int main(){
	Queue Q1;
	Queue Q2(10);
	std::cout << "Q1, Q2 & Q3 SIZE TEST:" << std::endl;
	std::cout << "Q1 SIZE: " << Q1.GetSize() << std::endl;
	std::cout << "Q2 SIZE: " << Q2.GetSize() << std::endl;
	std::cout << std::endl;
	std::cout << "Q1 ENQUEUE TEST:" << std::endl;
	for (int Index = 1; Index <= Q1.GetSize()+1; Index++){
		Q1.Enqueue(Index);
	};
	std::cout << std::endl;
	std::cout << "Q2 ENQUEUE TEST:" << std::endl;
	for (int Index = 1; Index <= Q2.GetSize()+1; Index++){
		Q2.Enqueue(Index);
	};
	std::cout << std::endl;
	std::cout << "Q1 DEQUEUE TEST:" << std::endl;
	for (int Index = 1; Index <= Q1.GetSize()+1; Index++){
		int DequeuedItem = Index;
		Q1.Dequeue(DequeuedItem);
	};
	std::cout << std::endl;
	std::cout << "Q2 DEQUEUE TEST:" << std::endl;
	for (int Index = 1; Index <= Q2.GetSize()+1; Index++){
		int DequeuedItem = Index;
		Q2.Dequeue(DequeuedItem);
	};
	std::cout << std::endl;
	std::cout << "RANDOM Q1 TESTS:" << std::endl;
	int DequeuedItem;
	std::cout << "[ENQUEUE]-------------------------" << std::endl;
	Q1.Enqueue(1);
	Q1.Enqueue(2);
	Q1.Enqueue(3);
	Q1.Enqueue(4);
	Q1.Enqueue(5);
	Q1.Enqueue(999);
	std::cout << "[DEQUEUE]-------------------------" << std::endl;
	Q1.Dequeue(DequeuedItem);
	Q1.Dequeue(DequeuedItem);
	Q1.Dequeue(DequeuedItem);
	std::cout << "[ENQUEUE]-------------------------" << std::endl;
	Q1.Enqueue(6);
	Q1.Enqueue(7);
	Q1.Enqueue(8);
	Q1.Enqueue(999);
	std::cout << "[DEQUEUE]-------------------------" << std::endl;
	Q1.Dequeue(DequeuedItem);
	Q1.Dequeue(DequeuedItem);
	Q1.Dequeue(DequeuedItem);
	Q1.Dequeue(DequeuedItem);
	Q1.Dequeue(DequeuedItem);
	Q1.Dequeue(DequeuedItem);
	std::cout << "[ENQUEUE]-------------------------" << std::endl;
	Q1.Enqueue(9);
	Q1.Enqueue(10);
	Q1.Enqueue(11);
	std::cout << "[DEQUEUE]-------------------------" << std::endl;
	Q1.Dequeue(DequeuedItem);
	Q1.Dequeue(DequeuedItem);
	std::cout << "[ENQUEUE]-------------------------" << std::endl;
	Q1.Enqueue(12);
	Q1.Enqueue(13);
	Q1.Enqueue(14);
	Q1.Enqueue(15);
	Q1.Enqueue(999);
	std::cout << "[DEQUEUE]-------------------------" << std::endl;
	Q1.Dequeue(DequeuedItem);
	Q1.Dequeue(DequeuedItem);
	Q1.Dequeue(DequeuedItem);
	Q1.Dequeue(DequeuedItem);
	std::cout << "[ENQUEUE]-------------------------" << std::endl;
	Q1.Enqueue(16);
	Q1.Enqueue(17);
	std::cout << "[DEQUEUE]-------------------------" << std::endl;
	Q1.Dequeue(DequeuedItem);
	std::cout << "[ENQUEUE]-------------------------" << std::endl;
	Q1.Enqueue(18);
	std::cout << "[DEQUEUE]-------------------------" << std::endl;
	Q1.Dequeue(DequeuedItem);
	Q1.Dequeue(DequeuedItem);
	std::cout << "[ENQUEUE]-------------------------" << std::endl;
	Q1.Enqueue(19);
	Q1.Enqueue(20);
	Q1.Enqueue(21);
	Q1.Enqueue(22);
	Q1.Enqueue(999);
	std::cout << "[DEQUEUE]-------------------------" << std::endl;
	Q1.Dequeue(DequeuedItem);
	Q1.Dequeue(DequeuedItem);
	std::cout << "[ENQUEUE]-------------------------" << std::endl;
	Q1.Enqueue(23);
	std::cout << "[DEQUEUE]-------------------------" << std::endl;
	Q1.Dequeue(DequeuedItem);
	Q1.Dequeue(DequeuedItem);
	Q1.Dequeue(DequeuedItem);
	Q1.Dequeue(DequeuedItem);
	std::cout << "[ENQUEUE]-------------------------" << std::endl;
	Q1.Enqueue(24);
	std::cout << "[DEQUEUE]-------------------------" << std::endl;
	Q1.Dequeue(DequeuedItem);
	std::cout << "[ENQUEUE]-------------------------" << std::endl;
	Q1.Enqueue(25);
	std::cout << "[DEQUEUE]-------------------------" << std::endl;
	Q1.Dequeue(DequeuedItem);
	std::cout << "[ENQUEUE]-------------------------" << std::endl;
	Q1.Enqueue(26);
	Q1.Enqueue(27);
	Q1.Enqueue(28);
	Q1.Enqueue(29);
	Q1.Enqueue(30);
	Q1.Enqueue(999);
	std::cout << "[DEQUEUE]-------------------------" << std::endl;
	Q1.Dequeue(DequeuedItem);
	Q1.Dequeue(DequeuedItem);
	Q1.Dequeue(DequeuedItem);
	Q1.Dequeue(DequeuedItem);
	Q1.Dequeue(DequeuedItem);
	Q1.Dequeue(DequeuedItem);
	std::cout << "[TESTING CUTTING IN LINE]-------------------------" << std::endl;
	Q1.CutInLine(1,0);
	Q1.CutInLine(2,0);
	Q1.CutInLine(3,0);
	Q1.CutInLine(4,0);
	Q1.CutInLine(5,0);
	Q1.CutInLine(999,0);
	Q1.Dequeue(DequeuedItem);
	Q1.Dequeue(DequeuedItem);
	Q1.Dequeue(DequeuedItem);
	Q1.Dequeue(DequeuedItem);
	Q1.Dequeue(DequeuedItem);
	Q1.Dequeue(DequeuedItem);
	Q1.Enqueue(1);
	Q1.Dequeue(DequeuedItem);
	Q1.Enqueue(1);
	Q1.Dequeue(DequeuedItem);
	Q1.Enqueue(1);
	Q1.Enqueue(2);
	Q1.Enqueue(3);
	Q1.Enqueue(4);
	Q1.CutInLine(5,2);
	Q1.Dequeue(DequeuedItem);
	Q1.Dequeue(DequeuedItem);
	Q1.Dequeue(DequeuedItem);
	Q1.Dequeue(DequeuedItem);
	Q1.Dequeue(DequeuedItem);
	Q1.Dequeue(DequeuedItem);
	return 0;
};