#include "LL.h"
#include <iostream>
using namespace std;
int main() {
	std::cout << "Linked List Class" << std::endl << std::endl;
	LL LinkedList = LL();
	std::cout << "[SYSTEM MESSAGE] Initial Linked List!" << std::endl;
	LinkedList.Print();
	std::cout << std::endl << "[SYSTEM MESSAGE] First Insert At Head!" << std::endl;
	LinkedList.Insert(0);
	LinkedList.Print();
	std::cout << std::endl << "[SYSTEM MESSAGE] Insert Before Head!" << std::endl;
	LinkedList.Insert(-2);
	LinkedList.Print();
	LinkedList.Insert(-4);
	LinkedList.Print();
	LinkedList.Insert(-6);
	LinkedList.Print();
	std::cout << std::endl << "[SYSTEM MESSAGE] Insert After Tail!" << std::endl;
	LinkedList.Insert(2);
	LinkedList.Print();
	LinkedList.Insert(4);
	LinkedList.Print();
	LinkedList.Insert(6);
	LinkedList.Print();
	std::cout << std::endl << "[SYSTEM MESSAGE] Insert Between Nodes!" << std::endl;
	LinkedList.Insert(-1);
	LinkedList.Print();
	LinkedList.Insert(-3);
	LinkedList.Print();
	LinkedList.Insert(-5);
	LinkedList.Print();
	LinkedList.Insert(1);
	LinkedList.Print();
	LinkedList.Insert(3);
	LinkedList.Print();
	LinkedList.Insert(5);
	LinkedList.Print();
	std::cout << std::endl << "[SYSTEM MESSAGE] Insert Duplicate Items!" << std::endl;
	LinkedList.Insert(-6);
	LinkedList.Insert(-5);
	LinkedList.Insert(-4);
	LinkedList.Insert(-3);
	LinkedList.Insert(-2);
	LinkedList.Insert(-1);
	LinkedList.Insert(0);
	LinkedList.Insert(1);
	LinkedList.Insert(2);
	LinkedList.Insert(3);
	LinkedList.Insert(4);
	LinkedList.Insert(5);
	LinkedList.Insert(6);
	LinkedList.Print();
	std::cout << std::endl << "[SYSTEM MESSAGE] Copy Constructor!" << std::endl;
	LL LinkListCopy = LL(LinkedList);
	LinkListCopy.Print();
	std::cout << std::endl << "[SYSTEM MESSAGE] Assignment Operator!" << std::endl;
	LL LinkList2 = LL();
	LinkList2.Insert(123);
	LinkList2.Insert(456);
	LinkList2.Insert(789);
	LL LinkListAssignmentOperator = LL();
	LinkListAssignmentOperator.Insert(100);
	LinkListAssignmentOperator.Insert(200);
	LinkListAssignmentOperator.Insert(300);
	LinkListAssignmentOperator.Insert(400);
	LinkListAssignmentOperator.Insert(500);
	LinkListAssignmentOperator.Insert(600);
	LinkListAssignmentOperator.Insert(700);
	LinkListAssignmentOperator.Insert(800);
	LinkListAssignmentOperator.Insert(900);
	std::cout << std::endl << "[SYSTEM MESSAGE] Before Assignment Operation!" << std::endl;
	std::cout << "[SYSTEM MESSAGE] LinkListAssignmentOperator:" << std::endl;
	LinkListAssignmentOperator.Print();
	std::cout << std::endl << "[SYSTEM MESSAGE] After Assignment Operation!" << std::endl;
	LinkListAssignmentOperator = LinkList2;
	std::cout << "[SYSTEM MESSAGE] LinkListAssignmentOperator:" << std::endl;
	LinkListAssignmentOperator.Print();
	std::cout << "[SYSTEM MESSAGE] LinkList2:" << std::endl;
	LinkList2.Print();
	std::cout << std::endl << "[SYSTEM MESSAGE] Remove Head Item!" << std::endl;
	LinkedList.Remove(-6);
	LinkedList.Print();
	std::cout << std::endl << "[SYSTEM MESSAGE] Remove Item Not In Linked List!" << std::endl;
	LinkedList.Remove(-6);
	LinkedList.Print();
	std::cout << std::endl << "[SYSTEM MESSAGE] Remove Tail Item!" << std::endl;
	LinkedList.Remove(6);
	LinkedList.Print();
	std::cout << std::endl << "[SYSTEM MESSAGE] Remove 2nd Node!" << std::endl;
	LinkedList.Remove(-4);
	LinkedList.Print();
	std::cout << std::endl << "[SYSTEM MESSAGE] Remove 2nd To Last Node!" << std::endl;
	LinkedList.Remove(4);
	LinkedList.Print();
	std::cout << std::endl << "[SYSTEM MESSAGE] Remove 3rd Node!" << std::endl;
	LinkedList.Remove(-2);
	LinkedList.Print();
	std::cout << std::endl << "[SYSTEM MESSAGE] Remove 3rd To Last Node!" << std::endl;
	LinkedList.Remove(2);
	LinkedList.Print();
	std::cout << std::endl << "[SYSTEM MESSAGE] Remove Center Node!" << std::endl;
	LinkedList.Remove(0);
	LinkedList.Print();
	std::cout << std::endl << "[SYSTEM MESSAGE] Remove Every Node!" << std::endl;
	LinkedList.Remove(-1);
	LinkedList.Print();
	LinkedList.Remove(1);
	LinkedList.Print();
	LinkedList.Remove(-3);
	LinkedList.Print();
	LinkedList.Remove(3);
	LinkedList.Print();
	LinkedList.Remove(-5);
	LinkedList.Print();
	LinkedList.Remove(5);
	LinkedList.Print();
	std::cout << std::endl << "[SYSTEM MESSAGE] Remove A Node From An Empty Linked List!" << std::endl;
	LinkedList.Remove(999);
	LinkedList.Print();
	std::cout << "[SYSTEM MESSAGE] LinkedList:" << std::endl;
	LinkedList.Print();
	std::cout << "[SYSTEM MESSAGE] LinkListCopy:" << std::endl;
	LinkListCopy.Print();
	std::cout << "[SYSTEM MESSAGE] LinkListAssignmentOperator:" << std::endl;
	LinkListAssignmentOperator.Print();
	std::cout << "[SYSTEM MESSAGE] LinkList2:" << std::endl;
	LinkList2.Print();
	std::cout << std::endl << "[SYSTEM MESSAGE] Program Terminated..." << std::endl;
	return 0;
};